### ISSUE TITLE
Modification to multi_thread_read.py

### ISSUE THREAD

**Issue by GuidoStefanutoAllseas** [marnixteunissen/Anomaly_detection#3]
Hi Marnix,
Please change the following things on lines:
- 150: make "project" required = False
- 129: check if it runs the IF, even when plot=false (it does in my case for some reason)
- 87: if "project" is none, then "offset" should be 0

**Comment by marnixteunissen** [comment]
implemented changes to code, tested if plot was not specified, which does not show the plot on my version
